"""
Django settings for LineBot project.

Generated by 'django-admin startproject' using Django 3.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path
import os
import environ


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Initialize environment variables
env = environ.Env()
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', default=env('SECRET_KEY'))

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = 'RENDER' not in os.environ
DEBUG = True

ALLOWED_HOSTS = []
if RENDER_EXTERNAL_HOSTNAME := os.environ.get('RENDER_EXTERNAL_HOSTNAME', default=env('RENDER_EXTERNAL_HOSTNAME')):
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_extensions',
    'BotTest'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'LineBot.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'LineBot.wsgi.application'

# Redis 快取。本地 docker-compose 提供的 redis 預設在 redis:6379
REDIS_LOCATION = os.environ.get('REDIS_LOCATION', default=env('REDIS_LOCATION', default='redis://redis:6379/0'))
REDIS_PASSWORD = os.environ.get('REDIS_PASSWORD', default=env('REDIS_PASSWORD', default=None))

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": REDIS_LOCATION,
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "PASSWORD": REDIS_PASSWORD
        },
        "KEY_PREFIX": "Cache"
    }
}

# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases
# 用環境變數 DB_ENGINE 切換 sqlite / mysql（預設 mysql）
#  - sqlite: DB_ENGINE=sqlite（配合 DATABASE_PATH 指定 .sqlite3 檔）
#  - mysql : DB_ENGINE=mysql（配合 MYSQL_HOST/USER/PASSWORD/NAME）
DB_ENGINE = os.environ.get('DB_ENGINE', default=env('DB_ENGINE', default='mysql'))

if DB_ENGINE == 'sqlite':
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': os.environ.get('DATABASE_PATH', default=str(BASE_DIR / 'db.sqlite3')),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': os.environ.get('MYSQL_NAME', default=env('MYSQL_NAME', default='LineBot')),
            'HOST': os.environ.get('MYSQL_HOST', default=env('MYSQL_HOST', default='mysql')),
            'PORT': int(os.environ.get('MYSQL_PORT', default=env('MYSQL_PORT', default='3306'))),
            'USER': os.environ.get('MYSQL_USER', default=env('MYSQL_USER', default='root')),
            'PASSWORD': os.environ.get('MYSQL_PASSWORD', default=env('MYSQL_PASSWORD', default='password')),
        }
    }


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Taipei'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = 'static'

# LINE BOT SECRET
LINE_CHANNEL_ACCESS_TOKEN = os.environ.get('LINE_CHANNEL_ACCESS_TOKEN', default=env('LINE_CHANNEL_ACCESS_TOKEN'))
LINE_CHANNEL_SECRET = os.environ.get('LINE_CHANNEL_SECRET', default=env('LINE_CHANNEL_SECRET'))

# YOUTUBE API
YOUTUBE_API_KEY = os.environ.get('YOUTUBE_API_KEY', default=env('YOUTUBE_API_KEY'))

# Weather API
WEATHER_API_KEY = os.environ.get('WEATHER_API_KEY', default=env('WEATHER_API_KEY'))

# OpenAI API
OPEN_AI_API_KEY = os.environ.get('OPEN_AI_API_KEY', default=env('OPEN_AI_API_KEY'))

# GIPHY API
GIPHY_API_KEY = os.environ.get('GIPHY_API_KEY', default=env('GIPHY_API_KEY', default=''))

# GEMINI API
GEMINI_API_KEY = os.environ.get('GEMINI_API_KEY', default=env('GEMINI_API_KEY', default=''))
