# Generated by Django 4.1.1 on 2022-10-31 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BotTest', '0003_lineuser_dailyattendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
